ERROR 1: TIFFFillTile:Read error at row 7680, col 6656, tile 456; got 548114 bytes, expected 756557
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: /vsicurl/https://naipeuwest.blob.core.windows.net/naip/v002/nh/2021/nh_060cm_2021/42071/m_4207115_sw_19_060_20211024.tif, band 1: IReadBlock failed at X offset 16, Y offset 22: TIFFReadEncodedTile() failed.
Traceback (most recent call last):
  File "rasterio/_io.pyx", line 975, in rasterio._io.DatasetReaderBase._read
  File "rasterio/_io.pyx", line 213, in rasterio._io.io_multi_band
  File "rasterio/_err.pyx", line 195, in rasterio._err.exc_wrap_int
rasterio._err.CPLE_AppDefinedError: /vsicurl/https://naipeuwest.blob.core.windows.net/naip/v002/nh/2021/nh_060cm_2021/42071/m_4207115_sw_19_060_20211024.tif, band 1: IReadBlock failed at X offset 16, Y offset 22: TIFFReadEncodedTile() failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hpc/home/csr33/ast_object_detection/predict_preprocessing.py", line 101, in <module>
    # Get the arguments
    ^^^^^^^^^^
  File "/hpc/home/csr33/ast_object_detection/predict_preprocessing.py", line 92, in main
    naip_df = pd.read_parquet(args.naip_tile_df) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/csr33/ast_object_detection/predict_preprocessing.py", line 69, in data_processing_over_chunk
    
  File "/hpc/home/csr33/ast_object_detection/predict_preprocessing.py", line 49, in data_processing
    split_tile_values = [s.values.tolist() for s in split_tile]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/csr33/ast_object_detection/predict_preprocessing.py", line 49, in <listcomp>
    split_tile_values = [s.values.tolist() for s in split_tile]
                         ^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/dataarray.py", line 769, in values
    return self.variable.values
           ^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/variable.py", line 556, in values
    return _as_array_or_item(self._data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/variable.py", line 306, in _as_array_or_item
    data = np.asarray(data)
           ^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/indexing.py", line 696, in __array__
    return np.asarray(self.get_duck_array(), dtype=dtype)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/indexing.py", line 699, in get_duck_array
    self._ensure_cached()
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/indexing.py", line 693, in _ensure_cached
    self.array = as_indexable(self.array.get_duck_array())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/indexing.py", line 667, in get_duck_array
    return self.array.get_duck_array()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/indexing.py", line 554, in get_duck_array
    array = self.array[self.key]
            ~~~~~~~~~~^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/rioxarray/_io.py", line 453, in __getitem__
    return indexing.explicit_indexing_adapter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/xarray/core/indexing.py", line 861, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/rioxarray/_io.py", line 430, in _getitem
    out = riods.read(band_key, window=window, masked=self.masked)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rasterio/_io.pyx", line 651, in rasterio._io.DatasetReaderBase.read
  File "rasterio/_io.pyx", line 978, in rasterio._io.DatasetReaderBase._read
rasterio.errors.RasterioIOError: Read or write failed. /vsicurl/https://naipeuwest.blob.core.windows.net/naip/v002/nh/2021/nh_060cm_2021/42071/m_4207115_sw_19_060_20211024.tif, band 1: IReadBlock failed at X offset 16, Y offset 22: TIFFReadEncodedTile() failed.
