Traceback (most recent call last):
  File "/hpc/home/csr33/ast_object_detection/src/predict.py", line 343, in <module>
    predict(args)
  File "/hpc/home/csr33/ast_object_detection/src/predict.py", line 334, in predict
    predict_df.to_file(os.path.join(args.prediction_dir, f"predictions_{args.chunk_id}.geojson"), 
    ^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/yolov8/lib/python3.11/site-packages/pandas/core/generic.py", line 6293, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'to_file'. Did you mean: 'to_pickle'?
